# Generated by Django 5.0.7 on 2024-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('content', models.CharField(max_length=500)),
                ('free', models.IntegerField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
    ]
