# Generated by Django 5.0.7 on 2024-08-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='programs',
            new_name='training',
        ),
    ]
