# Generated by Django 5.0.7 on 2024-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0003_training_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
