# Generated by Django 5.0.7 on 2024-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0004_alter_training_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='training',
            name='description2',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='main_description',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
