# Generated by Django 5.0.7 on 2024-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0005_rename_description_training_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('logins', models.CharField(max_length=250, verbose_name='Логин')),
                ('passwords', models.CharField(max_length=250, verbose_name='Пароль')),
                ('gender', models.SlugField(max_length=250, verbose_name='Пароль')),
            ],
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Программы тренировок', 'verbose_name_plural': 'Программы тренировок'},
        ),
        migrations.AlterField(
            model_name='training',
            name='content',
            field=models.CharField(max_length=500, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='training',
            name='free',
            field=models.IntegerField(verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='имя'),
        ),
    ]
