# Generated by Django 5.0.7 on 2024-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0006_data_people_alter_training_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя отправителя')),
                ('reviews', models.CharField(max_length=250)),
            ],
        ),
    ]
