# Generated by Django 5.0.7 on 2024-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0007_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='user', max_length=250, verbose_name='Имя отправителя'),
        ),
    ]
