# Generated by Django 5.0.7 on 2024-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0009_myusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myusers',
            options={'verbose_name': 'Доп данные для User', 'verbose_name_plural': 'Доп данные для User'},
        ),
    ]
