# Generated by Django 5.0.7 on 2024-09-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0010_alter_myusers_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='date_bitrh',
            field=models.CharField(max_length=255, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add', to=settings.AUTH_USER_MODEL),
        ),
    ]
