# Generated by Django 5.0.7 on 2024-09-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0011_alter_myusers_date_bitrh_alter_myusers_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='add', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
