# Generated by Django 5.0.7 on 2024-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0013_myusers_id_alter_myusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
