# Generated by Django 5.0.7 on 2024-09-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0018_alter_myusers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='date_bitrh',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
