# Generated by Django 5.0.7 on 2024-09-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0019_alter_myusers_date_bitrh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы участников'},
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.CharField(max_length=250, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='training',
            name='content',
            field=models.CharField(max_length=500, verbose_name='Основной контент'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description1',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Поле параграфа 1'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description2',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Поле параграфа 2'),
        ),
        migrations.AlterField(
            model_name='training',
            name='main_description',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Индивидуальный основной контент'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Отображение url'),
        ),
    ]
