# Generated by Django 5.0.7 on 2024-09-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0020_alter_reviews_options_alter_reviews_reviews_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзывы участников', 'verbose_name_plural': 'Отзывы участников'},
        ),
    ]
