# Generated by Django 5.0.7 on 2024-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chuvash_Workout', '0021_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='description1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True, verbose_name='Поле параграфа 1'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True, verbose_name='Поле параграфа 2'),
        ),
        migrations.AlterField(
            model_name='training',
            name='main_description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True, verbose_name='Индивидуальный основной контент'),
        ),
    ]
